//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_Table
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string Messages { get; set; }
        public string Verification_Code { get; set; }
    
        public virtual User_Table User_Table { get; set; }
    }
}
